Update nuget.yml
Signed-off-by: Derek Gooding <djgooding@live.com>

diff --git a/.github/workflows/nuget.yml b/.github/workflows/nuget.yml
--- a/.github/workflows/nuget.yml
+++ b/.github/workflows/nuget.yml
@@ -53,7 +53,13 @@ jobs:
         run: |
           dotnet pack ConsoleHero/ConsoleHero.csproj --configuration Release --no-build --output ./nupkg
           mkdir -p ./nupkg/analyzers/dotnet/cs/
+          if [ -f EnumSourceGenerator/bin/Release/netstandard2.0/EnumSourceGenerator.dll ]; then
+          echo "Source Generator DLL found, copying..."
           cp EnumSourceGenerator/bin/Release/netstandard2.0/EnumSourceGenerator.dll ./nupkg/analyzers/dotnet/cs/
+          else
+            echo "Source Generator DLL not found! Exiting."
+            exit 1
+          fi
 
       - name: Publish to NuGet
         if: env.run_publish == 'true'
